### ISSUE TITLE
success is undefined

### ISSUE THREAD

**Issue by ryyppy** [youknowriad/rungen#3]
Huh... that's weird:

``` js
//test.js
import {create} from 'rungen'

function* myGenerator() {
  yield 'test'; 
}

const runtime = create();
const onSuccess = value => console.log('success : ' + value);
const onError = error => console.log('error : ' + error);

runtime(myGenerator(), onSuccess, onError)
```

Run it with babel (+es2015-preset) and get this output:

```
babel-node test.js
success : undefined
```

Need to run!

**Comment by youknowriad** [comment]
It's the desired behavior, the `success` will receive the return value of the generator, so you may want to change the generator like this:

``` javascript
function* myGenerator() {
  return yield 'test';
}
```

you can take a look here :-) http://www.webpackbin.com/Vy96phf1M

**Comment by ryyppy** [comment]
Okay, something is completely off with the documentation... maybe I will reiterate the examples in your README and create a PR... thanks for the example!
